#!/bin/bash

echo "######################################"
echo "#                                    #"
echo "#   浙江大学NESC课题组物联网实验室   #"
echo "#      IoT Lab of ZJU NESC Group     #"
echo "#                                    #"
echo "######################################"
echo ""

cd $(dirname $0)

dir_cmd=`pwd`
dir=$dir_cmd

echo ""
echo "Please configure manually!"
echo ""
echo "DB SERVER : "
echo " 1.MongoDB configuration"
echo "    hint1   : mgd_add_app_user.sh"
echo "    hint2.1 : db.createUser({user:\"USER1\",pwd:\"PWD1\",roles:[{role:"readWrite",db:\"data\"},{role:\"readWrite\",db:\"udp\"}]})"
echo "    hint2.2 : db.createUser({user:\"USER2\",pwd:\"PWD2\",roles:[{role:"readWrite",db:\"fota_dev_1908\"}]})"
echo "    hint2.3 : Write rcloud_configuration.properties(USER1) / deploy.env(USER2)"
echo "    hint3   : vim /etc/mongod.conf"
echo "    hint4   : systemctl enable mongod"
echo "    hint5   : service mongod restart"
echo " 2.MySQL configuration"
echo "    hint1.1 : mysql -u root -p"
echo "    hint1.2 : > SET PASSWORD FOR 'root'@'localhost' = PASSWORD('NEWPASSWD');"
echo "    hint2   : vim /etc/my.cnf"
echo "    hint3   : vim ./script/deploy.env"
echo "    hint4   : mysql_init.sh"
echo "    hint5   : systemctl enable mysqld"
echo " 3.crontab run ./script/updateCpuMemDisk4Db.sh"
echo "    hint1.1 : crontab -e"
echo "    hint1.2 : 0 1 * * * $dir/script/updateCpuMemDisk4Db.sh"
echo "    hint2   : systemctl enable crond"
echo ""
echo "APP SERVER : "
echo " 1.Redis startup when reboot"
echo "    hint1   : systemctl enable redis"
echo " 2.Docker startup when reboot"
echo "    hint1   : systemctl enable docker"
echo " 3.crontab run ./script/updateCpuMemDisk4App.sh"
echo "    hint1.1 : crontab -e"
echo "    hint1.2 : */20 * * * * $dir/script/updateCpuMemDisk4App.sh"
echo "    hint2   : systemctl enable crond"
echo " 4.rcloud_configuration.properties configure"
echo "    hint1   : server.props.addr auto changed by step4_startup.sh"
echo " 5.deploy.env"

